# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x07metrics\"e\n\x0eMetricsRequest\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x11\n\tdevice_id\x18\x05 \x01(\t\"\"\n\x0fMetricsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa5\x01\n\x0eMetricsService\x12\x42\n\x0bSendMetrics\x12\x17.metrics.MetricsRequest\x1a\x18.metrics.MetricsResponse\"\x00\x12O\n\x16SendMetricsStreamReply\x12\x17.metrics.MetricsRequest\x1a\x18.metrics.MetricsResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_METRICSREQUEST']._serialized_start=26
  _globals['_METRICSREQUEST']._serialized_end=127
  _globals['_METRICSRESPONSE']._serialized_start=129
  _globals['_METRICSRESPONSE']._serialized_end=163
  _globals['_METRICSSERVICE']._serialized_start=166
  _globals['_METRICSSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
